/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package batalha_naval.frames;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Lucas
 */
public final class EndGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form EndGameFrame
     * @param won
     * @param restartMap
     */
    public EndGameFrame( boolean won, int[][] restartMap ) 
    {
        initComponents();
        setLocationRelativeTo(null);
        
        this.restartMap = restartMap;
        
        if( !won )
        {
            informationLabel.setForeground( Color.red );
            informationLabel.setText( "Você Perdeu" );
        }                
        
        setListenerOnButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationLabel = new javax.swing.JLabel();
        restartGame = new javax.swing.JButton();
        newGame = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setResizable(false);
        getContentPane().setLayout(null);

        informationLabel.setFont(new java.awt.Font("Lucida Sans", 3, 84)); // NOI18N
        informationLabel.setForeground(new java.awt.Color(144, 238, 144));
        informationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informationLabel.setText("Você Ganhou");
        informationLabel.setToolTipText("");
        getContentPane().add(informationLabel);
        informationLabel.setBounds(200, 30, 1020, 300);

        restartGame.setBackground(new java.awt.Color(102, 102, 255));
        restartGame.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        restartGame.setText("Reiniciar Jogo");
        getContentPane().add(restartGame);
        restartGame.setBounds(620, 390, 200, 40);

        newGame.setBackground(new java.awt.Color(102, 102, 255));
        newGame.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        newGame.setText("Novo Jogo");
        newGame.setActionCommand("");
        getContentPane().add(newGame);
        newGame.setBounds(620, 490, 200, 40);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backgrounds/background_final_frame.jpg"))); // NOI18N
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 1440, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public void setListenerOnButtons()
    {
        newGame.addActionListener( new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                CreateGameFrame createGameFrame = new CreateGameFrame( null );
                
                createGameFrame.setVisible( true );
                
                dispose();
            }
        });
        
        restartGame.addActionListener( new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                CreateGameFrame createGameFrame = new CreateGameFrame( restartMap );
                
                createGameFrame.setVisible( true );
                
                dispose();
            }
        });
    }
    
    private final int[][] restartMap;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JButton newGame;
    private javax.swing.JButton restartGame;
    // End of variables declaration//GEN-END:variables
}
