/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package batalha_naval.frames;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Lucas
 */
public final class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() 
    {     
        initComponents();
        setLocationRelativeTo(null);
        addListenerToStartButton();
    }
    
    public void addListenerToStartButton()
    {
        startButton.addMouseListener( new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent e) 
            {
               CreateGameFrame createGameFrame = new CreateGameFrame( null );
               
               createGameFrame.setVisible( true );

               dispose();
            }            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setPreferredSize(new java.awt.Dimension(1440, 900));
        setResizable(false);
        getContentPane().setLayout(null);

        startButton.setBackground(new java.awt.Color(0, 204, 204));
        startButton.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        startButton.setText("Iniciar Jogo");
        startButton.setToolTipText("");
        startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        startButton.setFocusPainted(false);
        getContentPane().add(startButton);
        startButton.setBounds(620, 50, 250, 80);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backgrounds/background_main_frame.jpg"))); // NOI18N
        backgroundImage.setToolTipText("");
        backgroundImage.setPreferredSize(getPreferredSize());
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 1440, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
